export const BEGIN_EDITING = 'BEGIN_EDITING';
export const BEGIN_NEW = 'BEGIN_NEW';
export const UPDATE_EDITABLE = 'UPDATE_EDITABLE';
export const STOP_EDITING = 'STOP_EDITING';

export const OPTIMISTIC_UPDATE = 'OPTIMISTIC_UPDATE';
export const CANCEL_OPTIMISTIC_UPDATE = 'CANCEL_OPTIMISTIC_UPDATE';
